name: Build plugin

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm run pot
      - name: Build zip
        run: zip -r cdb-form.zip . -x '*.git*' 'node_modules/*'
      - uses: actions/upload-artifact@v4
        with:
          name: cdb-form
          path: cdb-form.zip
